repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=90"]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--line-length=90"]
        exclude: >
          (?x)^(
              \.git/.*|
              \.venv/.*
          )$

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        language_version: python3.12
        args:
          [
            "--max-line-length=100",
            "--extend-ignore=E203,W503",
            "--per-file-ignores=__init__.py:F401",
          ]
        exclude: >
          (?x)^(
              \.git/.*|
              \.venv/.*|
              \.dockerignore
          )$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: denet_api
        args:
          [
            "--config-file=pyproject.toml",
            "--no-implicit-reexport",
            "--show-error-context",
            "--verbose",
            "--explicit-package-bases",
          ]
        files: ^src/
        additional_dependencies:
          - mypy==1.13.0
          - types-ujson
